### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by slincoln-aiq** [SigmaHQ/pySigma-backend-opensearch#3]
@andurin would you mind creating a new release on PyPI when you get a chance? I currently cannot install this backend with `pip` or `poetry` using `pySigma==0.11.3`. I made a PR for the pySigma version increase a few months ago that was accepted, just need a PyPI release so we can use it.

Thanks!

**Comment by andurin** [comment]
@slincoln-aiq Done and thanks for the reminder.
